apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2 #executa 2 instancias do back p alta disponibilidade
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: lascoski/projetofinancas-backend:1.0.1
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/mydatabase" #URL interna do K8s para o banco de dados sua string de conexao